/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'shardendu' at '8/11/16 8:45 PM' with Gradle 2.13
 *
 * @author shardendu, @date 8/11/16 8:45 PM
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
